// Default setup tasks pre-seeded for new Company Builder installations
// These are inserted on first use via the "Initialisieren" button

interface DefaultTask {
  section: string;
  title: string;
  description: string;
  whyImportant: string;
  required: boolean;
  priority: string;
  phase: string;
  blockerGoLive: boolean;
  blockerFirstDeal: boolean;
  evidenceRequired?: string;
  externalAdvisor?: string;
  sortOrder: number;
}

export const DEFAULT_TASKS: DefaultTask[] = [

  // ── 1. Strategische Grundlage ─────────────────────────────────────────────
  {
    section: 'strategie', sortOrder: 10,
    title: 'Geschäftsmodell definieren & dokumentieren',
    description: 'Unternehmenzweck, Handelsmodus (Eigenhandel/Vermittlung), Rolle im Warenfluss, B2B/B2C, Zielländer und Ursprungsländer festlegen.',
    whyImportant: 'Davon hängen Rechtsform, Versicherungen, Zollrolle, Verträge und Kapitalbedarf ab. Ohne klares Modell werden alle Folgeschritte unsauber.',
    required: true, priority: 'kritisch', phase: 'idee',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Schriftliche Dokumentation des Geschäftsmodells',
  },
  {
    section: 'strategie', sortOrder: 20,
    title: 'Handelsrolle im ersten Geschäft festlegen',
    description: 'Entscheidung: Händler auf eigene Rechnung, Broker/Vermittler, Handelsagent, Distributor oder Export-Management-Service?',
    whyImportant: 'Bestimmt Haftung, Zahlungsrisiko, Vertragsstruktur und steuerliche Behandlung grundlegend.',
    required: true, priority: 'kritisch', phase: 'idee',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Entscheidungsprotokoll mit Begründung',
  },
  {
    section: 'strategie', sortOrder: 30,
    title: 'Zielprodukte und Zielmärkte definieren',
    description: 'Startprodukt(e) und -länder festlegen. Fokus auf ein Produkt oder mehrere? Erster Testdeal oder direkt Container?',
    whyImportant: 'Verhindert Überdehnung. Klarer Fokus ermöglicht schnellere Operationalisierung.',
    required: true, priority: 'hoch', phase: 'idee',
    blockerGoLive: false, blockerFirstDeal: true,
  },
  {
    section: 'strategie', sortOrder: 40,
    title: 'Rollen & Verantwortlichkeiten klären',
    description: 'Gründer, Gesellschafter, Geschäftsführer und operative Rollen definieren. Wer unterschreibt Verträge? Wer gibt Zahlungen frei?',
    whyImportant: 'Ohne klare Verantwortung entstehen Sicherheitslücken und operative Engpässe bei ersten Deals.',
    required: true, priority: 'hoch', phase: 'vorgruendung',
    blockerGoLive: true, blockerFirstDeal: false,
    evidenceRequired: 'Rollenverteilung / RACI-Matrix',
  },
  {
    section: 'strategie', sortOrder: 50,
    title: 'Startkapital & Finanzierungsmodell klären',
    description: 'Eigenkapital, Darlehen, Warenfinanzierung, Factoring und Liquiditätsbedarf für erste 6 Monate berechnen.',
    whyImportant: 'Exportgeschäft bindet Kapital lange (Vorauszahlung → Lieferung → Käuferzahlung). Ohne Plan droht Liquiditätsengpass.',
    required: true, priority: 'hoch', phase: 'vorgruendung',
    blockerGoLive: false, blockerFirstDeal: false,
    evidenceRequired: 'Finanzplan / Liquiditätsplanung',
  },
  {
    section: 'strategie', sortOrder: 60,
    title: '12-Monats-Roadmap erstellen',
    description: 'Aufbau-Phasen mit Meilensteinen definieren: Gründung, Testdeal, erster Container, Lieferantenbasis, Käuferpipeline.',
    whyImportant: 'Verhindert unkontrolliertes Wachstum. Setzt realistische Erwartungen für Team und Investoren.',
    required: false, priority: 'mittel', phase: 'idee',
    blockerGoLive: false, blockerFirstDeal: false,
  },
  {
    section: 'strategie', sortOrder: 70,
    title: 'Wettbewerbs- und Marktanalyse',
    description: 'Wer sind Wettbewerber? Was sind aktuelle Marktpreise? Welche Käufergruppen sind erreichbar?',
    whyImportant: 'Fundiert Preisstrategie und Vertriebsansatz. Wichtig für erste Investor- oder Bankgespräche.',
    required: false, priority: 'niedrig', phase: 'idee',
    blockerGoLive: false, blockerFirstDeal: false,
  },

  // ── 2. Rechtsform & Gründung ──────────────────────────────────────────────
  {
    section: 'gruendung', sortOrder: 10,
    title: 'Rechtsform entscheiden und dokumentieren',
    description: 'Abwägen zwischen Einzelunternehmen, UG, GmbH, GmbH & Co. KG anhand Haftung, Kapital, Außenwirkung, Steuern.',
    whyImportant: 'Bestimmt Haftungsrisiko, Buchhaltungspflichten, Kreditwürdigkeit und Vertragsbeziehungen dauerhaft.',
    required: true, priority: 'kritisch', phase: 'vorgruendung',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Entscheidungsprotokoll mit geprüften Alternativen',
    externalAdvisor: 'Steuerberater / Anwalt',
  },
  {
    section: 'gruendung', sortOrder: 20,
    title: 'Firmennamen wählen, Verfügbarkeit prüfen',
    description: 'Name auf Handelsregister-Tauglichkeit, Markenschutz, Domain und Social-Media-Handles prüfen.',
    whyImportant: 'Nachträgliche Namensänderung kostet Zeit, Geld und Glaubwürdigkeit.',
    required: true, priority: 'hoch', phase: 'vorgruendung',
    blockerGoLive: true, blockerFirstDeal: false,
    evidenceRequired: 'Namensprüfung Markenamt + Domain-Sicherung',
  },
  {
    section: 'gruendung', sortOrder: 30,
    title: 'Steuerberater und ggf. Anwalt beauftragen',
    description: 'Geeigneten Steuerberater (Exporterfahrung empfohlen) und Anwalt für Gesellschaftsrecht finden.',
    whyImportant: 'Fehler bei Gründung, Steuern und Verträgen können sehr teuer werden. Professionelle Begleitung unbedingt empfohlen.',
    required: true, priority: 'kritisch', phase: 'vorgruendung',
    blockerGoLive: true, blockerFirstDeal: false,
    externalAdvisor: 'Steuerberater',
  },
  {
    section: 'gruendung', sortOrder: 40,
    title: 'Gesellschaftsvertrag / Gründungsdokumente vorbereiten',
    description: 'Musterprotokoll oder individueller Gesellschaftsvertrag: Gesellschafterliste, GF-Bestellung, Stammkapital, Gegenstand, Vertretung.',
    whyImportant: 'Ohne rechtssichere Dokumente kann keine Registrierung erfolgen.',
    required: true, priority: 'kritisch', phase: 'gruendung',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Gesellschaftsvertrag (unterschrieben / notariell)',
    externalAdvisor: 'Notar / Anwalt',
  },
  {
    section: 'gruendung', sortOrder: 50,
    title: 'Notartermin & Handelsregisteranmeldung (falls GmbH/UG)',
    description: 'Notariell beglaubigte Gründung, Einzahlung Stammkapital, Handelsregisteranmeldung durchführen.',
    whyImportant: 'Ohne Handelsregistereintrag keine Rechtsfähigkeit der GmbH/UG.',
    required: false, priority: 'kritisch', phase: 'gruendung',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Handelsregistereintrag / HR-Auszug',
    externalAdvisor: 'Notar',
  },
  {
    section: 'gruendung', sortOrder: 60,
    title: 'Gewerbeanmeldung beim Gewerbeamt',
    description: 'Tätigkeitsbeschreibung, Betriebsstätte, Beginn der Tätigkeit, Haupt-/Nebenerwerb anmelden.',
    whyImportant: 'Ohne Gewerbeanmeldung keine legale Geschäftstätigkeit. Löst steuerliche Erfassung aus.',
    required: true, priority: 'kritisch', phase: 'gruendung',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Upload Gewerbeschein',
  },

  // ── 3. Steuern, IDs & Behörden ─────────────────────────────────────────────
  {
    section: 'steuern', sortOrder: 10,
    title: 'Fragebogen zur steuerlichen Erfassung einreichen',
    description: 'ELSTER-Zugang einrichten, Fragebogen ausfüllen und innerhalb eines Monats nach Gründung elektronisch einreichen.',
    whyImportant: 'Pflichtschritt nach Gewerbeanmeldung. Ohne steuerliche Erfassung keine Steuernummer, keine Rechnungen, kein Vorsteuerabzug.',
    required: true, priority: 'kritisch', phase: 'gruendung',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'ELSTER-Einreichungsbestätigung',
    externalAdvisor: 'Steuerberater / Finanzamt',
  },
  {
    section: 'steuern', sortOrder: 20,
    title: 'Steuernummer erhalten und hinterlegen',
    description: 'Steuernummer vom Finanzamt erhalten, in System und Rechnungsvorlage hinterlegen.',
    whyImportant: 'Ohne Steuernummer keine rechtsgültige Rechnung ausstellbar.',
    required: true, priority: 'kritisch', phase: 'gruendung',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Schreiben Finanzamt mit Steuernummer',
  },
  {
    section: 'steuern', sortOrder: 30,
    title: 'Umsatzsteuer-ID (USt-ID) beantragen',
    description: 'USt-ID beim Bundeszentralamt für Steuern beantragen. Wichtig für B2B-Geschäfte mit EU-Partnern.',
    whyImportant: 'Für innergemeinschaftliche Lieferungen und steuerfreie EU-B2B-Geschäfte zwingend erforderlich.',
    required: true, priority: 'hoch', phase: 'gruendung',
    blockerGoLive: false, blockerFirstDeal: false,
    evidenceRequired: 'USt-ID Bestätigung',
    externalAdvisor: 'Bundeszentralamt für Steuern',
  },
  {
    section: 'steuern', sortOrder: 40,
    title: 'EORI-Nummer beantragen',
    description: 'EORI (Economic Operators Registration and Identification) kostenlos über das Zoll-Portal beantragen. Identifiziert Unternehmen im Zollverfahren.',
    whyImportant: 'Ohne EORI-Nummer sind Import-/Exportabwicklungen mit Zollbezug nicht möglich. Kritischer Blocker für erste Lieferung.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'EORI-Bestätigung vom Zoll-Portal',
    externalAdvisor: 'Zoll-Portal / Zollagent',
  },
  {
    section: 'steuern', sortOrder: 50,
    title: 'IHK-Mitgliedschaft klären',
    description: 'Pflichtmitgliedschaft bei IHK prüfen und ggf. anmelden. IHK-Leistungen (Ursprungszeugnisse, Beratung) kennenlernen.',
    whyImportant: 'In Deutschland Pflichtmitgliedschaft für Gewerbetreibende. IHK stellt Ursprungszeugnisse und bietet Export-Beratung an.',
    required: true, priority: 'hoch', phase: 'gruendung',
    blockerGoLive: false, blockerFirstDeal: false,
    externalAdvisor: 'IHK',
  },
  {
    section: 'steuern', sortOrder: 60,
    title: 'Berufsgenossenschaft anmelden',
    description: 'Bei der zuständigen Berufsgenossenschaft anmelden (auch ohne Mitarbeiter für Selbstständige relevant).',
    whyImportant: 'Gesetzliche Pflicht in Deutschland. Bei Nicht-Anmeldung drohen Nachzahlungen und Bußgelder.',
    required: true, priority: 'hoch', phase: 'gruendung',
    blockerGoLive: false, blockerFirstDeal: false,
  },
  {
    section: 'steuern', sortOrder: 70,
    title: 'Transparenzregister-Pflicht prüfen',
    description: 'Wirtschaftlich Berechtigte (ab 25% Beteiligung) im Transparenzregister eintragen lassen.',
    whyImportant: 'Seit 2021 Pflicht in Deutschland. Bußgelder bis 1 Mio. € bei Verstoß.',
    required: true, priority: 'hoch', phase: 'gruendung',
    blockerGoLive: false, blockerFirstDeal: false,
    externalAdvisor: 'Transparenzregister.de',
  },
  {
    section: 'steuern', sortOrder: 80,
    title: 'EUDR- und CBAM-Relevanz prüfen',
    description: 'Prüfen ob Produkte unter EU Deforestation Regulation oder Carbon Border Adjustment Mechanism fallen. Mit Zollagent/IHK abklären.',
    whyImportant: 'Verstöße können zu Importverboten und Bußgeldern führen. Frühzeitig klären spart Aufwand.',
    required: false, priority: 'mittel', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
    externalAdvisor: 'Zollagent / IHK / Steuerberater',
  },

  // ── 4. Banking & Finanzen ─────────────────────────────────────────────────
  {
    section: 'banking', sortOrder: 10,
    title: 'Geschäftskonto eröffnen',
    description: 'Bank auswählen, Geschäftskonto eröffnen, Online-Banking einrichten, Berechtigungen und 4-Augen-Prinzip aktivieren.',
    whyImportant: 'Ohne Geschäftskonto keine professionellen Zahlungen, keine Lieferantenzahlungen, keine Käuferüberweisung.',
    required: true, priority: 'kritisch', phase: 'gruendung',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Kontoöffnungsbestätigung mit IBAN',
  },
  {
    section: 'banking', sortOrder: 20,
    title: 'Zahlungsfreigabe-Regeln definieren',
    description: 'Wer darf Zahlungen anlegen? Ab welchem Betrag zweite Freigabe? Neue Bankdaten immer telefonisch bestätigen. Prozess dokumentieren.',
    whyImportant: 'Betrugsprävention. Ohne klare Regeln drohen Betrug durch gefälschte Rechnungen und Bankdaten.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: true, blockerFirstDeal: true,
    evidenceRequired: 'Schriftlich dokumentierte Zahlungsrichtlinie',
  },
  {
    section: 'banking', sortOrder: 30,
    title: 'Buchhaltungssystem einrichten',
    description: 'Buchhaltungstool auswählen (z.B. DATEV, Lexware, Debitoor), Kontenrahmen, Steuerberaterzugang, Belegablage, Kostenstellen.',
    whyImportant: 'Ohne saubere Buchhaltung keine Steuererklärung, kein Kostenüberblick, keine Kalkulationsbasis für Deals.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: true, blockerFirstDeal: false,
    externalAdvisor: 'Steuerberater',
  },
  {
    section: 'banking', sortOrder: 40,
    title: 'Finanzplan & Kapitalbedarf erstellen',
    description: 'Gründungskosten, laufende Fixkosten, Warenfinanzierung, Fracht, Zoll, Versicherung, Reserve und Liquiditätspuffer kalkulieren.',
    whyImportant: 'Exportgeschäft bindet erheblich Kapital. Ohne Plan droht Liquiditätsengpass genau dann wenn der erste Deal kommt.',
    required: true, priority: 'hoch', phase: 'vorgruendung',
    blockerGoLive: false, blockerFirstDeal: false,
    evidenceRequired: 'Liquiditätsplan für 12 Monate',
  },
  {
    section: 'banking', sortOrder: 50,
    title: 'Fremdwährungskonto prüfen (USD, EUR)',
    description: 'Prüfen ob USD- oder Fremdwährungskonto benötigt. Viele Exportgeschäfte laufen in USD — Wechselkursrisiko absichern.',
    whyImportant: 'Ohne Fremdwährungskonto entstehen hohe Wechselkosten und Kursrisiken bei USD-Geschäften.',
    required: false, priority: 'mittel', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
  },
  {
    section: 'banking', sortOrder: 60,
    title: 'Trade Finance / Warenfinanzierung prüfen',
    description: 'Factoring, Letter of Credit, Kreditlinie, Warenkreditversicherung und Fördermittel (z.B. KfW) prüfen.',
    whyImportant: 'Ermöglicht größere Deals ohne vollständige Eigenkapitalfinanzierung. Wichtig für Skalierung.',
    required: false, priority: 'niedrig', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
  },

  // ── 5. Versicherungen & Risiko ────────────────────────────────────────────
  {
    section: 'versicherung', sortOrder: 10,
    title: 'Betriebshaftpflicht abschließen',
    description: 'Betriebshaftpflichtversicherung für Schäden Dritter durch die Geschäftstätigkeit abschließen.',
    whyImportant: 'Grundlegende Absicherung für jedes Unternehmen. Ohne sie haftet GF persönlich für viele Schäden.',
    required: true, priority: 'kritisch', phase: 'gruendung',
    blockerGoLive: true, blockerFirstDeal: false,
    evidenceRequired: 'Versicherungspolice',
  },
  {
    section: 'versicherung', sortOrder: 20,
    title: 'Transportversicherung klären',
    description: 'Pro-Sendung-Versicherung oder Jahrespolice für Warenschäden während Transport (Seefracht, Luftfracht, Inland).',
    whyImportant: 'Bei Warenwert von 50.000–500.000 € pro Sendung ist Verlust oder Schaden ohne Versicherung existenzbedrohend.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    externalAdvisor: 'Versicherungsmakler / Spediteur',
  },
  {
    section: 'versicherung', sortOrder: 30,
    title: 'Produkthaftpflicht prüfen',
    description: 'Für Schäden durch Produkte (insb. Lebensmittel, chemische Produkte, Konsumgüter) Produkthaftpflicht prüfen.',
    whyImportant: 'Lebensmittelrückrufe oder Produktschäden können ohne Versicherung zur Insolvenz führen.',
    required: false, priority: 'hoch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
    externalAdvisor: 'Versicherungsmakler',
  },
  {
    section: 'versicherung', sortOrder: 40,
    title: 'Forderungsausfall-/Kreditversicherung prüfen',
    description: 'Absicherung falls Käufer nicht zahlt. Wichtig bei großen Warenwerten und unbekannten Käufern.',
    whyImportant: 'Forderungsausfall bei Exportgeschäft kann erheblichen Schaden verursachen und Unternehmen gefährden.',
    required: false, priority: 'hoch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
  },
  {
    section: 'versicherung', sortOrder: 50,
    title: 'Vermögensschadenshaftpflicht prüfen',
    description: 'Für reine Vermögensschäden durch Fehler bei Beratung, Dokumentation oder Vertretung.',
    whyImportant: 'Relevant bei Handelsvertretern und Brokern die im Namen Dritter handeln.',
    required: false, priority: 'mittel', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
  },

  // ── 6. Verträge, Recht & Dokumente ─────────────────────────────────────────
  {
    section: 'recht', sortOrder: 10,
    title: 'Lieferantenvertrag-Vorlage erstellen',
    description: 'Rahmenliefervertrag mit Qualitätsspezifikation, Preis, Mengentoleranz, Liefertermin, Dokumentenpflichten, Reklamationsfristen.',
    whyImportant: 'Ohne Vertrag kein rechtlicher Schutz bei Qualitätsproblemen, Lieferverzug oder Betrug.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    evidenceRequired: 'Vorlage (Entwurf oder geprüfte Version)',
    externalAdvisor: 'Anwalt',
  },
  {
    section: 'recht', sortOrder: 20,
    title: 'Käufervertrag-Vorlage / Sales Contract erstellen',
    description: 'Kaufvertrag mit Incoterm, Zahlungsbedingungen, Qualitätsspezifikation, Dokumentenpflichten, Gerichtsstand.',
    whyImportant: 'Schützt vor Zahlungsausfällen, Qualitätsstreitigkeiten und unklarer Haftung beim Käufer.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    externalAdvisor: 'Anwalt',
  },
  {
    section: 'recht', sortOrder: 30,
    title: 'Exportdokumentenvorlagen (CI, PL, Proforma)',
    description: 'Commercial Invoice, Packing List und Proforma Invoice als Vorlagen mit Pflichtfeldern erstellen.',
    whyImportant: 'Fehlerhafte Exportdokumente blockieren Zollabfertigung und Käuferzahlung.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    evidenceRequired: 'Ausgefülltes Testbeispiel',
  },
  {
    section: 'recht', sortOrder: 40,
    title: 'Pflichtklauseln-Bibliothek definieren',
    description: 'Standardklauseln zu: Incoterms, Zahlungsbedingungen, Qualitätstoleranz, Force Majeure, Sanktionen, Streitbeilegung.',
    whyImportant: 'Schützt vor rechtlichen Lücken in Verträgen. Spart Zeit bei jedem neuen Deal.',
    required: true, priority: 'hoch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
  },
  {
    section: 'recht', sortOrder: 50,
    title: 'NDA-Vorlage erstellen',
    description: 'Geheimhaltungsvereinbarung für Lieferanten, Käufer und Dienstleister.',
    whyImportant: 'Schützt Geschäftskontakte, Produktinformationen und Konditionen vor Weitergabe.',
    required: false, priority: 'hoch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
  },
  {
    section: 'recht', sortOrder: 60,
    title: 'Vertragsvorlagen anwaltlich prüfen lassen',
    description: 'Alle Vertragsvorlagen durch Anwalt mit Exporterfahrung prüfen lassen.',
    whyImportant: 'Rechtsfehler in Standardverträgen können bei erstem Streitfall sehr teuer werden.',
    required: true, priority: 'hoch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
    externalAdvisor: 'Anwalt (Handels-/Exportrecht)',
  },
  {
    section: 'recht', sortOrder: 70,
    title: 'DSGVO / Datenschutz sicherstellen',
    description: 'Datenschutzerklärung, Verarbeitungsverzeichnis, Einwilligungen und technische Maßnahmen prüfen.',
    whyImportant: 'Pflicht in Deutschland/EU. Bußgelder bis 4% des Jahresumsatzes.',
    required: true, priority: 'mittel', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: false,
    externalAdvisor: 'Datenschutzbeauftragter / Anwalt',
  },

  // ── 7. Exportfähigkeit & Infrastruktur ───────────────────────────────────
  {
    section: 'export', sortOrder: 10,
    title: 'Startprodukt definieren und HS-Code ermitteln',
    description: 'Konkretes Startprodukt mit HS-Code, Qualitätsstandard, Käuferanforderungen und Verpackungsvorgaben definieren.',
    whyImportant: 'Ohne klaren HS-Code sind Zollanmeldung, Dokumentation und Margenberechnung nicht möglich.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    externalAdvisor: 'Zollagent',
  },
  {
    section: 'export', sortOrder: 20,
    title: 'Ersten Lieferanten qualifizieren',
    description: 'Lieferant mit Onboarding-Checkliste qualifizieren: Identität, Kapazität, Qualitätsnachweise, GPS, Bank, Exporterfahrung.',
    whyImportant: 'Ohne geprüften Lieferanten kein verlässlicher Deal. Ungeprüfte Lieferanten erhöhen Betrugs- und Qualitätsrisiko.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    evidenceRequired: 'Ausgefüllter Lieferanten-Onboarding-Fragebogen',
  },
  {
    section: 'export', sortOrder: 30,
    title: 'Produktkalkulation erstellen',
    description: 'Einstandspreis, Frachtkosten, Zoll, Versicherung, Dokumenten, Marge und Mindestverkaufspreis berechnen.',
    whyImportant: 'Ohne belastbare Kalkulation kann kein profitabler Preis angeboten werden.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    evidenceRequired: 'Kalkulationsvorlage mit Beispielwerten',
  },
  {
    section: 'export', sortOrder: 40,
    title: 'Spediteur anfragen und beauftragen',
    description: 'Geeigneten Spediteur für die geplanten Handelsrouten (Herkunftsland → Bestimmungsland) finden und Angebot einholen.',
    whyImportant: 'Ohne Spediteur keine Buchung von Fracht, keine Containerverfügbarkeit, keine Hafenabwicklung.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
  },
  {
    section: 'export', sortOrder: 50,
    title: 'Zollagent finden und beauftragen',
    description: 'Zollagent für Ausfuhranmeldung (Deutschland) und Einfuhranmeldung im Bestimmungsland beauftragen.',
    whyImportant: 'Ohne Zollagent keine rechtskonforme Zollabwicklung. Fehler können zu Lieferverzug und Strafen führen.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    externalAdvisor: 'Zollagent',
  },
  {
    section: 'export', sortOrder: 60,
    title: 'Dokumentenmatrix erstellen',
    description: 'Pro Handelsroute und Produkttyp: welche Dokumente werden wann von wem benötigt?',
    whyImportant: 'Fehlende Dokumente sind häufigste Ursache für Lieferverzug und Käuferreklamationen.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
    evidenceRequired: 'Ausgefüllte Dokumentenmatrix',
  },
  {
    section: 'export', sortOrder: 70,
    title: 'Qualitätsstandard und QC-Prozess definieren',
    description: 'Produktspezifikation, Prüfpunkte vor Versand, Musterfreigabeprozess und Reklamationsprozess dokumentieren.',
    whyImportant: 'Qualitätsprobleme sind häufigste Ursache für Käuferreklamationen und Reputationsschaden.',
    required: true, priority: 'hoch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
  },
  {
    section: 'export', sortOrder: 80,
    title: 'Incoterm-Standard festlegen und dokumentieren',
    description: 'Standard-Incoterm für Lieferantenbeziehungen (z.B. FOB) und Käuferbeziehungen (z.B. CIF/DAP) festlegen.',
    whyImportant: 'Incoterms bestimmen Gefahrenübergang, Versicherungspflichten und Kostentragung. Falsche Wahl kann teuer werden.',
    required: true, priority: 'hoch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
  },
  {
    section: 'export', sortOrder: 90,
    title: 'Zahlungsbedingungen mit Lieferant und Käufer definieren',
    description: 'Zahlungsmodalitäten festlegen: Vorauszahlung, Anzahlung, L/C, D/P, offene Rechnung — mit Risikobewertung.',
    whyImportant: 'Falsche Zahlungsbedingungen führen zu Liquiditätsengpass oder unkontrollierbarem Forderungsrisiko.',
    required: true, priority: 'kritisch', phase: 'setup',
    blockerGoLive: false, blockerFirstDeal: true,
  },

  // ── 8. Go-Live & erste Deals ──────────────────────────────────────────────
  {
    section: 'golive', sortOrder: 10,
    title: 'Ersten Käuferkontakt aufbauen',
    description: 'Ersten qualifizierten Käufer identifizieren, kontaktieren und Interesse für Produktmuster bestätigen.',
    whyImportant: 'Ohne aktiven Käufer kein Deal, kein Umsatz, keine Lernkurve.',
    required: true, priority: 'kritisch', phase: 'go_live',
    blockerGoLive: false, blockerFirstDeal: true,
  },
  {
    section: 'golive', sortOrder: 20,
    title: 'Musterprozess durchführen',
    description: 'Muster beim Lieferanten bestellen, auf Qualität prüfen und an Käufer versenden. Feedback dokumentieren.',
    whyImportant: 'Muster reduzieren das Risiko bei erstem Container erheblich. Fast jeder professionelle Käufer erwartet Muster.',
    required: true, priority: 'kritisch', phase: 'go_live',
    blockerGoLive: false, blockerFirstDeal: true,
    evidenceRequired: 'Musterversandnachweis + Käuferfeedback',
  },
  {
    section: 'golive', sortOrder: 30,
    title: 'Go-Live-Check vollständig durchführen',
    description: 'Alle kritischen Blocker prüfen: Konto, Steuernummer, EORI, Verträge, Kalkulation, Lieferant, Käufer, Dokumente.',
    whyImportant: 'Verhindert dass kritische Lücken erst im laufenden Deal auffallen und teuer werden.',
    required: true, priority: 'kritisch', phase: 'go_live',
    blockerGoLive: true, blockerFirstDeal: true,
  },
  {
    section: 'golive', sortOrder: 40,
    title: 'Ersten realen Exportdeal starten',
    description: 'Kaufvertrag mit Käufer unterzeichnen, Lieferant beauftragen, Versand planen und Deal im System anlegen.',
    whyImportant: 'Der erste Deal ist die wichtigste Lernkurve und bestätigt die operative Bereitschaft des Unternehmens.',
    required: true, priority: 'kritisch', phase: 'go_live',
    blockerGoLive: false, blockerFirstDeal: false,
  },
];
